# docker build -t angular/node_18/alpine -f Dockerfile.alpine_angular .

FROM node:18-alpine

RUN npm install --location=global vim
RUN npm install --location=global npm
RUN npm install --location=global jest -y
RUN npm install --location=global semistandard -y
RUN npm -g install @angular/cli -y
