# Dockerfile for C environment for development
FROM gcc

RUN apt-get update && apt-get upgrade -y
RUN apt-get install vim -y
RUN git clone https://github.com/holbertonschool/Betty.git
RUN apt-get install valgrind -y
