FROM ubuntu:trusty

RUN apt-get update && apt-get upgrade -y
RUN apt-get install vim -y
RUN apt-get install valgrind -y
RUN apt install build-essential -y
RUN apt-get install manpages-dev -y
RUN apt install git -y
RUN git clone https://github.com/holbertonschool/Betty.git
